-- Domestic — all migrations, concatenated.
--
-- GENERATED by scripts/bundle-sql.mjs. Do not edit; add a numbered file under
-- supabase/migrations/ and re-run `npm run sql:bundle`.
--
-- Paste the whole thing into the Supabase SQL editor and hit Run. Every
-- statement is idempotent, so running this again is a no-op — you do not need
-- to track which migrations you have already applied.
--
-- Contains: 0001_init.sql, 0002_logic.sql, 0003_invites_and_oauth.sql, 0004_multi_household.sql, 0005_modules.sql, 0006_devices.sql, 0007_intro.sql, 0008_pgcrypto_schema.sql, 0009_chore_admin.sql, 0010_recurring_expenses.sql, 0011_ai_config.sql

/**************************************************************************
 * 0001_init.sql
 *************************************************************************/

-- 526 Detroit St. — household chores + expenses
-- Core idea, taken straight from the paper chart on the fridge:
-- every chore owns a fixed rotation of roommates (AB -> BK -> TT -> NA) and a
-- monotonically increasing turn counter. Turn N belongs to
-- members[N % members.length]. Completing a turn materializes turn N+1.
-- Scheduled chores (Floors, weekly Trash) get a due date; on-demand chores
-- (Dishes per load, Trash when full) are just a numbered queue, like the
-- 16 numbered rows on the sheet.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- households

create table if not exists households (
  id          uuid primary key default gen_random_uuid(),
  name        text        not null,
  address     text,
  timezone    text        not null default 'America/Detroit',
  created_at  timestamptz not null default now()
);

create table if not exists profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  household_id  uuid        references households(id) on delete set null,
  full_name     text        not null,
  initials      text        not null,           -- 'AB', 'NA', 'TT', 'BK'
  email         text,
  color         text        not null default '#64748b',
  avatar_url    text,
  is_admin      boolean     not null default false,
  -- notification preferences
  notify_push   boolean     not null default true,
  notify_email  boolean     not null default false,
  quiet_from    smallint    not null default 22, -- local hour, inclusive
  quiet_to      smallint    not null default 8,  -- local hour, exclusive
  created_at    timestamptz not null default now()
);

create index if not exists profiles_household_id_idx on profiles (household_id);

-- ------------------------------------------------------------------- chores

do $$ begin
  create type chore_cadence as enum ('scheduled', 'on_demand');
exception when duplicate_object then null;
end $$;
do $$ begin
  create type turn_status as enum ('pending', 'done', 'skipped', 'missed');
exception when duplicate_object then null;
end $$;

create table if not exists chores (
  id             uuid primary key default gen_random_uuid(),
  household_id   uuid not null references households(id) on delete cascade,
  name           text not null,
  emoji          text not null default '🧹',
  description    text,
  cadence        chore_cadence not null,

  -- scheduled cadence: "every `interval_weeks` weeks, on these weekdays"
  -- 0 = Sunday .. 6 = Saturday.  Floors = {0,5}; Microwave = {6} every 2 wks.
  days_of_week   smallint[] not null default '{}',
  interval_weeks smallint   not null default 1,
  anchor_date    date       not null default current_date,
  due_hour       smallint   not null default 20,  -- local hour the turn is "due"

  -- on-demand cadence: how many turns to keep visible in the queue
  queue_depth    smallint   not null default 4,

  -- how far ahead scheduled turns are materialized
  lookahead_days smallint   not null default 21,

  sort_order     smallint   not null default 0,
  is_active      boolean    not null default true,
  created_at     timestamptz not null default now()
);

create index if not exists chores_household_id_is_active_idx on chores (household_id, is_active);

-- The rotation order for a chore. `position` is 0-based and defines the cycle.
create table if not exists chore_rotation (
  chore_id    uuid     not null references chores(id) on delete cascade,
  profile_id  uuid     not null references profiles(id) on delete cascade,
  position    smallint not null,
  primary key (chore_id, profile_id),
  unique (chore_id, position) deferrable initially deferred
);

-- One row = one box on the paper chart.
create table if not exists chore_turns (
  id            uuid primary key default gen_random_uuid(),
  chore_id      uuid     not null references chores(id) on delete cascade,
  household_id  uuid     not null references households(id) on delete cascade,
  turn_number   integer  not null,            -- monotonic, 0-based
  assignee_id   uuid     not null references profiles(id) on delete cascade,
  status        turn_status not null default 'pending',
  due_at        timestamptz,                  -- null for on-demand turns
  completed_at  timestamptz,
  completed_by  uuid     references profiles(id) on delete set null,
  note          text,
  created_at    timestamptz not null default now(),
  unique (chore_id, turn_number)
);

create index if not exists chore_turns_household_id_status_due_at_idx on chore_turns (household_id, status, due_at);
create index if not exists chore_turns_chore_id_status_turn_number_idx on chore_turns (chore_id, status, turn_number);
create index if not exists chore_turns_assignee_id_status_idx on chore_turns (assignee_id, status);

-- Swap a turn with another roommate. Requires the other person to accept.
create table if not exists chore_swaps (
  id            uuid primary key default gen_random_uuid(),
  turn_id       uuid not null references chore_turns(id) on delete cascade,
  requested_by  uuid not null references profiles(id) on delete cascade,
  requested_to  uuid not null references profiles(id) on delete cascade,
  status        text not null default 'pending'
                  check (status in ('pending','accepted','declined','cancelled')),
  message       text,
  created_at    timestamptz not null default now(),
  resolved_at   timestamptz
);

create index if not exists chore_swaps_requested_to_status_idx on chore_swaps (requested_to, status);

-- ----------------------------------------------------------------- expenses

do $$ begin
  create type split_kind as enum ('equal', 'exact', 'shares', 'percent');
exception when duplicate_object then null;
end $$;

create table if not exists expenses (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references households(id) on delete cascade,
  description   text not null,
  amount_cents  bigint not null check (amount_cents > 0),
  currency      char(3) not null default 'USD',
  category      text not null default 'general',
  paid_by       uuid not null references profiles(id) on delete restrict,
  spent_on      date not null default current_date,
  split_kind    split_kind not null default 'equal',
  receipt_url   text,
  note          text,
  created_by    uuid references profiles(id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz
);

create index if not exists expenses_household_id_spent_on_desc_idx on expenses (household_id, spent_on desc) where deleted_at is null;

-- Who owes what on a given expense. owed_cents across an expense must sum to
-- amount_cents; enforced in the app + a deferred trigger below.
create table if not exists expense_splits (
  expense_id  uuid   not null references expenses(id) on delete cascade,
  profile_id  uuid   not null references profiles(id) on delete cascade,
  owed_cents  bigint not null check (owed_cents >= 0),
  weight      numeric(10,4),   -- shares or percent, kept for re-editing
  primary key (expense_id, profile_id)
);

-- A real transfer of money between two roommates (Venmo, cash, etc).
create table if not exists settlements (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references households(id) on delete cascade,
  from_profile  uuid not null references profiles(id) on delete restrict,
  to_profile    uuid not null references profiles(id) on delete restrict,
  amount_cents  bigint not null check (amount_cents > 0),
  settled_on    date not null default current_date,
  method        text not null default 'venmo',
  note          text,
  created_by    uuid references profiles(id) on delete set null,
  created_at    timestamptz not null default now(),
  check (from_profile <> to_profile)
);

create index if not exists settlements_household_id_settled_on_desc_idx on settlements (household_id, settled_on desc);

-- ------------------------------------------------------- devices & activity

create table if not exists push_subscriptions (
  id          uuid primary key default gen_random_uuid(),
  profile_id  uuid not null references profiles(id) on delete cascade,
  endpoint    text not null unique,
  p256dh      text not null,
  auth        text not null,
  user_agent  text,
  created_at  timestamptz not null default now(),
  last_used_at timestamptz
);

create index if not exists push_subscriptions_profile_id_idx on push_subscriptions (profile_id);

-- The iPad on the wall. Authenticates with a bearer token instead of a user.
create table if not exists kiosk_devices (
  id            uuid primary key default gen_random_uuid(),
  household_id  uuid not null references households(id) on delete cascade,
  name          text not null,
  token_hash    text not null unique,
  last_seen_at  timestamptz,
  created_at    timestamptz not null default now()
);

create table if not exists activity_log (
  id            bigserial primary key,
  household_id  uuid not null references households(id) on delete cascade,
  actor_id      uuid references profiles(id) on delete set null,
  verb          text not null,          -- 'completed_chore', 'added_expense', ...
  summary       text not null,          -- pre-rendered, for the kiosk feed
  metadata      jsonb not null default '{}',
  created_at    timestamptz not null default now()
);

create index if not exists activity_log_household_id_created_at_desc_idx on activity_log (household_id, created_at desc);

-- ------------------------------------------------------------------- views

-- Net position per roommate. Positive => the household owes them money.
create or replace view v_balances with (security_invoker = true) as
with paid as (
  select e.household_id, e.paid_by as profile_id, sum(e.amount_cents) as cents
  from expenses e where e.deleted_at is null
  group by 1, 2
),
owed as (
  select e.household_id, s.profile_id, sum(s.owed_cents) as cents
  from expense_splits s
  join expenses e on e.id = s.expense_id and e.deleted_at is null
  group by 1, 2
),
sent as (
  select household_id, from_profile as profile_id, sum(amount_cents) as cents
  from settlements group by 1, 2
),
received as (
  select household_id, to_profile as profile_id, sum(amount_cents) as cents
  from settlements group by 1, 2
)
select
  p.household_id,
  p.id as profile_id,
  coalesce(paid.cents, 0)
    - coalesce(owed.cents, 0)
    + coalesce(sent.cents, 0)
    - coalesce(received.cents, 0) as net_cents
from profiles p
left join paid     on paid.profile_id     = p.id and paid.household_id     = p.household_id
left join owed     on owed.profile_id     = p.id and owed.household_id     = p.household_id
left join sent     on sent.profile_id     = p.id and sent.household_id     = p.household_id
left join received on received.profile_id = p.id and received.household_id = p.household_id
where p.household_id is not null;

-- Running tally of completed turns per person per chore — the digital version
-- of counting crossed-out initials on the sheet.
create or replace view v_chore_stats with (security_invoker = true) as
select
  t.household_id,
  t.chore_id,
  t.assignee_id as profile_id,
  count(*) filter (where t.status = 'done')    as done_count,
  count(*) filter (where t.status = 'missed')  as missed_count,
  max(t.completed_at)                          as last_done_at
from chore_turns t
group by 1, 2, 3;


/**************************************************************************
 * 0002_logic.sql
 *************************************************************************/

-- Rotation engine + row level security.

-- --------------------------------------------------------------- helpers

-- SECURITY DEFINER so RLS policies can call it without recursing into
-- the profiles policy that is itself being evaluated.
create or replace function current_household_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select household_id from profiles where id = auth.uid();
$$;

create or replace function is_household_member(target uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select target is not null and target = (
    select household_id from profiles where id = auth.uid()
  );
$$;

-- New auth user -> profile. Metadata is set at invite time.
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into profiles (id, email, full_name, initials, household_id)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'initials', upper(left(coalesce(new.raw_user_meta_data ->> 'full_name', new.email), 2))),
    (new.raw_user_meta_data ->> 'household_id')::uuid
  )
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ------------------------------------------------------- rotation engine

-- Who owns turn N of a chore?
create or replace function rotation_assignee(p_chore uuid, p_turn integer)
returns uuid
language plpgsql
stable
as $$
declare
  n int;
  who uuid;
begin
  select count(*) into n from chore_rotation where chore_rotation.chore_id = p_chore;
  if n = 0 then
    return null;
  end if;
  select profile_id into who
  from chore_rotation
  where chore_rotation.chore_id = p_chore
    and chore_rotation.position = (p_turn % n)
  limit 1;
  return who;
end;
$$;

-- Append the next turn in the cycle. Returns the new turn, or null if the
-- chore has no rotation configured.
create or replace function append_turn(p_chore uuid, p_due timestamptz default null)
returns chore_turns
language plpgsql
security definer
set search_path = public
as $$
declare
  next_no  int;
  who      uuid;
  hh       uuid;
  new_turn chore_turns;
begin
  select household_id into hh from chores where id = p_chore;
  select coalesce(max(turn_number), -1) + 1 into next_no
    from chore_turns where chore_id = p_chore;

  who := rotation_assignee(p_chore, next_no);
  if who is null then
    return null;
  end if;

  insert into chore_turns (chore_id, household_id, turn_number, assignee_id, due_at)
  values (p_chore, hh, next_no, who, p_due)
  returning * into new_turn;

  return new_turn;
end;
$$;

-- Keep `queue_depth` pending turns available for an on-demand chore, so the
-- kiosk can always show "up next" the way the numbered rows on the sheet do.
create or replace function top_up_queue(p_chore uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  want    int;
  have    int;
  made    int := 0;
begin
  select queue_depth into want from chores where id = p_chore and cadence = 'on_demand';
  if want is null then
    return 0;
  end if;

  select count(*) into have
    from chore_turns where chore_id = p_chore and status = 'pending';

  while have + made < want loop
    perform append_turn(p_chore, null);
    made := made + 1;
  end loop;

  return made;
end;
$$;

-- Materialize scheduled turns out to the chore's lookahead window.
-- A week is "on" when its offset from the anchor week is a multiple of
-- interval_weeks -- that is how "biweekly on weekends" stays in phase.
create or replace function materialize_schedule(p_chore uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  c        chores%rowtype;
  tz       text;
  cursor_d date;
  last_d   date;
  horizon  date;
  made     int := 0;
  wk_off   int;
  anchor_w date;
begin
  select * into c from chores where id = p_chore and cadence = 'scheduled' and is_active;
  if not found or array_length(c.days_of_week, 1) is null then
    return 0;
  end if;

  select timezone into tz from households where id = c.household_id;
  horizon  := (now() at time zone tz)::date + c.lookahead_days;
  anchor_w := date_trunc('week', c.anchor_date)::date;   -- Monday-based

  -- resume after the furthest turn we already created
  select max((due_at at time zone tz)::date) into last_d
    from chore_turns where chore_id = p_chore;

  cursor_d := greatest(
    coalesce(last_d + 1, c.anchor_date),
    (now() at time zone tz)::date
  );

  while cursor_d <= horizon loop
    wk_off := ((date_trunc('week', cursor_d)::date - anchor_w) / 7)::int;
    if (extract(dow from cursor_d)::smallint = any (c.days_of_week))
       and (wk_off % greatest(c.interval_weeks, 1) = 0) then
      perform append_turn(
        p_chore,
        ((cursor_d + make_interval(hours => c.due_hour)) at time zone tz)
      );
      made := made + 1;
    end if;
    cursor_d := cursor_d + 1;
  end loop;

  return made;
end;
$$;

-- Complete a turn and immediately open the next one, so there is never a
-- moment where nobody is "up".
create or replace function complete_turn(p_turn uuid, p_note text default null)
returns chore_turns
language plpgsql
security definer
set search_path = public
as $$
declare
  t   chore_turns%rowtype;
  c   chores%rowtype;
  me  uuid := auth.uid();
begin
  select * into t from chore_turns where id = p_turn for update;
  if not found then
    raise exception 'turn not found';
  end if;
  if not is_household_member(t.household_id) then
    raise exception 'not your household';
  end if;
  if t.status = 'done' then
    return t;
  end if;

  update chore_turns
     set status = 'done', completed_at = now(), completed_by = coalesce(me, t.assignee_id), note = p_note
   where id = p_turn
  returning * into t;

  select * into c from chores where id = t.chore_id;

  if c.cadence = 'on_demand' then
    perform top_up_queue(t.chore_id);
  else
    perform materialize_schedule(t.chore_id);
  end if;

  insert into activity_log (household_id, actor_id, verb, summary, metadata)
  select t.household_id, coalesce(me, t.assignee_id), 'completed_chore',
         p.full_name || ' did ' || c.name,
         jsonb_build_object('chore_id', c.id, 'turn_id', t.id, 'emoji', c.emoji)
  from profiles p where p.id = coalesce(me, t.assignee_id);

  return t;
end;
$$;

-- Called by the "dishwasher is full" / "trash is full" buttons: nothing to
-- create (the queue is already primed) but it timestamps the request and
-- pings whoever is up.
create or replace function flag_on_demand(p_chore uuid)
returns chore_turns
language plpgsql
security definer
set search_path = public
as $$
declare
  t chore_turns%rowtype;
  c chores%rowtype;
begin
  select * into c from chores where id = p_chore;
  if not is_household_member(c.household_id) then
    raise exception 'not your household';
  end if;

  perform top_up_queue(p_chore);

  select * into t from chore_turns
   where chore_id = p_chore and status = 'pending'
   order by turn_number limit 1;

  update chore_turns set due_at = now() where id = t.id and due_at is null;

  insert into activity_log (household_id, actor_id, verb, summary, metadata)
  select c.household_id, auth.uid(), 'flagged_chore',
         c.name || ' needs doing',
         jsonb_build_object('chore_id', c.id, 'turn_id', t.id, 'emoji', c.emoji);

  return t;
end;
$$;

-- Accepting a swap just reassigns the turn; the rotation itself is untouched,
-- so the cycle stays in order for everyone after.
create or replace function accept_swap(p_swap uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  s chore_swaps%rowtype;
begin
  select * into s from chore_swaps where id = p_swap for update;
  if not found or s.status <> 'pending' then
    raise exception 'swap not open';
  end if;
  if s.requested_to <> auth.uid() then
    raise exception 'not your swap to accept';
  end if;

  update chore_turns set assignee_id = s.requested_to where id = s.turn_id;
  update chore_swaps set status = 'accepted', resolved_at = now() where id = p_swap;
end;
$$;

-- ------------------------------------------------------------------- RLS

alter table households        enable row level security;
alter table profiles          enable row level security;
alter table chores            enable row level security;
alter table chore_rotation    enable row level security;
alter table chore_turns       enable row level security;
alter table chore_swaps       enable row level security;
alter table expenses          enable row level security;
alter table expense_splits    enable row level security;
alter table settlements       enable row level security;
alter table push_subscriptions enable row level security;
alter table kiosk_devices     enable row level security;
alter table activity_log      enable row level security;

drop policy if exists hh_read on households;
create policy hh_read on households for select
  using (id = current_household_id());

drop policy if exists pr_read on profiles;
create policy pr_read on profiles for select
  using (household_id = current_household_id() or id = auth.uid());
drop policy if exists pr_write on profiles;
create policy pr_write on profiles for update
  using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists ch_all on chores;
create policy ch_all on chores for all
  using (is_household_member(household_id))
  with check (is_household_member(household_id));

drop policy if exists rot_all on chore_rotation;
create policy rot_all on chore_rotation for all
  using (exists (select 1 from chores c where c.id = chore_id and is_household_member(c.household_id)))
  with check (exists (select 1 from chores c where c.id = chore_id and is_household_member(c.household_id)));

drop policy if exists turn_all on chore_turns;
create policy turn_all on chore_turns for all
  using (is_household_member(household_id))
  with check (is_household_member(household_id));

drop policy if exists swap_all on chore_swaps;
create policy swap_all on chore_swaps for all
  using (exists (select 1 from chore_turns t where t.id = turn_id and is_household_member(t.household_id)))
  with check (exists (select 1 from chore_turns t where t.id = turn_id and is_household_member(t.household_id)));

drop policy if exists exp_all on expenses;
create policy exp_all on expenses for all
  using (is_household_member(household_id))
  with check (is_household_member(household_id));

drop policy if exists split_all on expense_splits;
create policy split_all on expense_splits for all
  using (exists (select 1 from expenses e where e.id = expense_id and is_household_member(e.household_id)))
  with check (exists (select 1 from expenses e where e.id = expense_id and is_household_member(e.household_id)));

drop policy if exists settle_all on settlements;
create policy settle_all on settlements for all
  using (is_household_member(household_id))
  with check (is_household_member(household_id));

drop policy if exists push_own on push_subscriptions;
create policy push_own on push_subscriptions for all
  using (profile_id = auth.uid()) with check (profile_id = auth.uid());

drop policy if exists kiosk_read on kiosk_devices;
create policy kiosk_read on kiosk_devices for select
  using (is_household_member(household_id));

drop policy if exists act_read on activity_log;
create policy act_read on activity_log for select
  using (is_household_member(household_id));
drop policy if exists act_insert on activity_log;
create policy act_insert on activity_log for insert
  with check (is_household_member(household_id));

-- Views are created with security_invoker = true in 0001 so they honour the
-- caller's RLS rather than the view owner's.


/**************************************************************************
 * 0003_invites_and_oauth.sql
 *************************************************************************/

-- Run this on a database that already has 0001 and 0002.
--
-- Two changes:
--   1. Re-state security_invoker on the views in the exact form Supabase's
--      linter recognizes. `= on` and `= true` behave identically in Postgres,
--      but reloptions stores the literal token and the linter matches on
--      'true', so `on` gets reported as SECURITY DEFINER.
--   2. Decouple "who belongs to this household" from *how* they sign in, so
--      Google, magic link, or anything else all land in the right place.

alter view v_balances    set (security_invoker = true);
alter view v_chore_stats set (security_invoker = true);

-- ----------------------------------------------------------------- invites

-- The roster, keyed by email. Whoever first signs in with an invited address
-- gets that identity — name, initials, color, household — regardless of which
-- provider they used. Without this, a Google sign-in creates a profile with no
-- household and the app can only show "you're not in a household yet".
create table if not exists household_invites (
  email         text primary key,
  household_id  uuid not null references households(id) on delete cascade,
  full_name     text not null,
  initials      text not null,
  color         text not null default '#64748b',
  is_admin      boolean not null default false,
  created_at    timestamptz not null default now()
);

create index if not exists household_invites_household_idx
  on household_invites (household_id);

alter table household_invites enable row level security;

drop policy if exists inv_read on household_invites;
create policy inv_read on household_invites for select
  using (is_household_member(household_id));

-- ------------------------------------------------------------ new user hook

create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  inv       household_invites%rowtype;
  meta      jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  resolved  text;
begin
  -- Emails are case-insensitive in practice; invites should be too.
  select * into inv
  from household_invites
  where lower(household_invites.email) = lower(new.email);

  -- Google sends 'full_name' and/or 'name'; magic-link users have whatever the
  -- seed script set; fall back to the local part of the address.
  resolved := coalesce(
    inv.full_name,
    nullif(meta ->> 'full_name', ''),
    nullif(meta ->> 'name', ''),
    split_part(new.email, '@', 1)
  );

  insert into profiles (
    id, email, full_name, initials, household_id, color, avatar_url, is_admin
  )
  values (
    new.id,
    new.email,
    resolved,
    coalesce(inv.initials, nullif(meta ->> 'initials', ''), upper(left(resolved, 2))),
    coalesce(inv.household_id, (nullif(meta ->> 'household_id', ''))::uuid),
    coalesce(inv.color, '#64748b'),
    coalesce(nullif(meta ->> 'avatar_url', ''), nullif(meta ->> 'picture', '')),
    coalesce(inv.is_admin, false)
  )
  on conflict (id) do update set
    email      = excluded.email,
    -- Never clobber an established profile: a second identity linking to the
    -- same user (magic link, then Google) must not reset their household.
    full_name  = coalesce(profiles.full_name, excluded.full_name),
    avatar_url = coalesce(excluded.avatar_url, profiles.avatar_url),
    household_id = coalesce(profiles.household_id, excluded.household_id);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- Backfill invites for anyone already seeded, so the roster is complete even
-- if the household was set up before this migration existed.
-- Guarded by NOT EXISTS rather than ON CONFLICT: 0004 drops the email primary
-- key, so by the time this file is re-applied there is no unique constraint on
-- email for a conflict target to reference.
insert into household_invites (email, household_id, full_name, initials, color, is_admin)
select p.email, p.household_id, p.full_name, p.initials, p.color, p.is_admin
from profiles p
where p.email is not null
  and p.household_id is not null
  and not exists (
    select 1 from household_invites hi
    where lower(hi.email) = lower(p.email)
  );


/**************************************************************************
 * 0004_multi_household.sql
 *************************************************************************/

-- Turns Domestic from "one hardcoded house" into something any household can
-- deploy and run themselves.
--
--   * invites become shareable codes, not just pre-registered emails
--   * households are created in-app by whoever signs up first
--   * joining a household appends you to every rotation, mid-cycle, safely
--   * the kiosk is bound to a household by device record, not an env var
--   * closes a privilege escalation in the profiles update policy

/* ------------------------------------------------------------------ helpers */

create or replace function is_household_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from profiles where id = auth.uid()), false);
$$;

-- Crockford-ish alphabet: no I, L, O, U, 0 or 1, because these get read aloud
-- and typed on an iPad.
create or replace function generate_invite_code()
returns text
language plpgsql
volatile
as $$
declare
  alphabet text := '23456789ABCDEFGHJKMNPQRSTVWXYZ';
  candidate text;
  i int;
begin
  loop
    candidate := '';
    for i in 1..8 loop
      candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
      if i = 4 then candidate := candidate || '-'; end if;
    end loop;
    exit when not exists (select 1 from household_invites where code = candidate);
  end loop;
  return candidate;
end;
$$;

/* ------------------------------------------------------------- invite table */

-- 0003 keyed invites by email. Re-shape to a row-per-invite with a shareable
-- code; email becomes an optional restriction rather than the identity.
alter table household_invites
  add column if not exists id uuid not null default gen_random_uuid(),
  add column if not exists code text,
  add column if not exists created_by uuid references profiles(id) on delete set null,
  add column if not exists expires_at timestamptz,
  add column if not exists max_uses integer not null default 1,
  add column if not exists used_count integer not null default 0,
  add column if not exists revoked_at timestamptz;

update household_invites set code = generate_invite_code() where code is null;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'household_invites_pkey' and conrelid = 'household_invites'::regclass
  ) then
    alter table household_invites drop constraint household_invites_pkey;
  end if;
end $$;

-- In 0003 email was the primary key and full_name/initials were required. All
-- three are optional now: email restricts an invite to one address, and the
-- name fields are prefill hints on a link anyone can accept. These run after
-- the primary key is gone — you cannot drop NOT NULL from a PK column.
alter table household_invites alter column email     drop not null;
alter table household_invites alter column full_name drop not null;
alter table household_invites alter column initials  drop not null;

-- Default it too, so a hand-written insert (or the 0003 backfill) still gets a
-- usable code instead of failing the not-null.
alter table household_invites alter column code set default generate_invite_code();
alter table household_invites alter column code set not null;
alter table household_invites add primary key (id);

create unique index if not exists household_invites_code_key on household_invites (code);
create index if not exists household_invites_email_idx on household_invites (lower(email));

/* ------------------------------------------------------- rotation membership */

-- Pending turns are re-derived from the current rotation. Completed turns are
-- history and are never touched — otherwise adding a roommate would rewrite
-- who did the dishes last Tuesday.
create or replace function resync_pending_turns(p_chore uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare touched int := 0;
begin
  with fixed as (
    update chore_turns t
       set assignee_id = rotation_assignee(t.chore_id, t.turn_number)
     where t.chore_id = p_chore
       and t.status = 'pending'
       and t.assignee_id is distinct from rotation_assignee(t.chore_id, t.turn_number)
    returning 1
  )
  select count(*) into touched from fixed;
  return touched;
end;
$$;

-- Appends someone to the end of every active rotation in the household.
create or replace function add_to_rotations(p_profile uuid, p_household uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare c record;
begin
  for c in select id from chores where household_id = p_household and is_active loop
    if not exists (
      select 1 from chore_rotation
      where chore_id = c.id and profile_id = p_profile
    ) then
      insert into chore_rotation (chore_id, profile_id, position)
      select c.id, p_profile,
             coalesce(max(position), -1) + 1
      from chore_rotation where chore_id = c.id;

      perform resync_pending_turns(c.id);
    end if;
  end loop;
end;
$$;

-- Removing someone must close the gap in `position`, or `turn % n` starts
-- pointing at a hole and assignments go null.
create or replace function remove_from_rotations(p_profile uuid, p_household uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare c record;
begin
  for c in select id from chores where household_id = p_household loop
    delete from chore_rotation where chore_id = c.id and profile_id = p_profile;

    with renumbered as (
      select profile_id, row_number() over (order by position) - 1 as new_position
      from chore_rotation where chore_id = c.id
    )
    update chore_rotation r
       set position = renumbered.new_position
      from renumbered
     where r.chore_id = c.id and r.profile_id = renumbered.profile_id;

    perform resync_pending_turns(c.id);
  end loop;
end;
$$;

/* --------------------------------------------------------- create household */

create or replace function create_household(
  p_name      text,
  p_address   text default null,
  p_timezone  text default 'America/Detroit',
  p_full_name text default null,
  p_initials  text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  me       uuid := auth.uid();
  new_id   uuid;
  chore_id uuid;
  existing uuid;
begin
  if me is null then
    raise exception 'not signed in';
  end if;

  select household_id into existing from profiles where id = me;
  if existing is not null then
    raise exception 'you are already in a household';
  end if;

  insert into households (name, address, timezone)
  values (trim(p_name), nullif(trim(coalesce(p_address, '')), ''), p_timezone)
  returning id into new_id;

  update profiles
     set household_id = new_id,
         is_admin     = true,
         full_name    = coalesce(nullif(trim(coalesce(p_full_name, '')), ''), full_name),
         initials     = coalesce(nullif(upper(trim(coalesce(p_initials, ''))), ''), initials)
   where id = me;

  -- A starter set. Every field is editable afterwards; the point is that a new
  -- household has something on the board instead of an empty screen.
  for chore_id in
    insert into chores (household_id, name, emoji, description, cadence,
                        days_of_week, interval_weeks, due_hour, queue_depth, sort_order)
    values
      (new_id, 'Floors', '🧹', 'Sweep and mop the common areas', 'scheduled', '{0,5}', 1, 20, 4, 1),
      (new_id, 'Microwave', '🍲', 'Wipe out the microwave', 'scheduled', '{6}', 2, 20, 4, 2),
      (new_id, 'Trash to curb', '🗑️', 'Bins out the night before pickup', 'scheduled', '{0}', 1, 19, 4, 3),
      (new_id, 'Dishes', '🍽️', 'Run and unload a load', 'on_demand', '{}', 1, 20, 4, 4),
      (new_id, 'Trash when full', '🚮', 'Swap the kitchen bag', 'on_demand', '{}', 1, 20, 4, 5)
    returning id
  loop
    insert into chore_rotation (chore_id, profile_id, position) values (chore_id, me, 0);
  end loop;

  -- Fill the board so the first screen isn't empty.
  for chore_id in select id from chores where household_id = new_id loop
    if (select cadence from chores where id = chore_id) = 'scheduled' then
      perform materialize_schedule(chore_id);
    else
      perform top_up_queue(chore_id);
    end if;
  end loop;

  insert into activity_log (household_id, actor_id, verb, summary)
  values (new_id, me, 'created_household',
          (select full_name from profiles where id = me) || ' started the house');

  return new_id;
end;
$$;

/* ---------------------------------------------------------------- invites */

create or replace function create_invite(
  p_email      text default null,
  p_full_name  text default null,
  p_initials   text default null,
  p_color      text default '#64748b',
  p_expires_in interval default interval '14 days',
  p_max_uses   integer default 1
)
returns household_invites
language plpgsql
security definer
set search_path = public
as $$
declare
  me   uuid := auth.uid();
  hh   uuid;
  row_out household_invites;
begin
  select household_id into hh from profiles where id = me;
  if hh is null then raise exception 'you are not in a household'; end if;
  if not is_household_admin() then raise exception 'only an admin can invite people'; end if;

  insert into household_invites (
    household_id, code, email, full_name, initials, color,
    created_by, expires_at, max_uses
  )
  values (
    hh, generate_invite_code(), nullif(lower(trim(coalesce(p_email, ''))), ''),
    nullif(trim(coalesce(p_full_name, '')), ''),
    nullif(upper(trim(coalesce(p_initials, ''))), ''),
    coalesce(p_color, '#64748b'),
    me,
    case when p_expires_in is null then null else now() + p_expires_in end,
    greatest(coalesce(p_max_uses, 1), 1)
  )
  returning * into row_out;

  return row_out;
end;
$$;

create or replace function revoke_invite(p_invite uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  if not is_household_admin() then raise exception 'only an admin can revoke invites'; end if;
  select household_id into hh from profiles where id = auth.uid();

  update household_invites
     set revoked_at = now()
   where id = p_invite and household_id = hh and revoked_at is null;
end;
$$;

-- What a signed-in user sees before accepting, so the join screen can say
-- which house they are about to join without leaking anything else.
create or replace function peek_invite(p_code text)
returns table (household_name text, full_name text, initials text, valid boolean, reason text)
language plpgsql
security definer
set search_path = public
as $$
declare
  inv household_invites%rowtype;
  my_email text;
begin
  select * into inv from household_invites
   where upper(code) = upper(trim(p_code));

  if not found then
    return query select null::text, null::text, null::text, false, 'That code does not exist.';
    return;
  end if;

  select email into my_email from profiles where id = auth.uid();

  if inv.revoked_at is not null then
    return query select null::text, null::text, null::text, false, 'That invite was revoked.';
  elsif inv.expires_at is not null and inv.expires_at < now() then
    return query select null::text, null::text, null::text, false, 'That invite has expired.';
  elsif inv.used_count >= inv.max_uses then
    return query select null::text, null::text, null::text, false, 'That invite has already been used.';
  elsif inv.email is not null and lower(inv.email) is distinct from lower(coalesce(my_email, '')) then
    return query select null::text, null::text, null::text, false,
                        'That invite was issued to a different email address.';
  else
    return query
      select h.name, inv.full_name, inv.initials, true, null::text
      from households h where h.id = inv.household_id;
  end if;
end;
$$;

create or replace function redeem_invite(
  p_code      text,
  p_full_name text default null,
  p_initials  text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  me       uuid := auth.uid();
  inv      household_invites%rowtype;
  my_email text;
  existing uuid;
  resolved_name text;
begin
  if me is null then raise exception 'not signed in'; end if;

  select household_id, email into existing, my_email from profiles where id = me;
  if existing is not null then raise exception 'you are already in a household'; end if;

  -- Lock the row: two people redeeming a single-use code at the same moment
  -- must not both get in.
  select * into inv from household_invites
   where upper(code) = upper(trim(p_code))
   for update;

  if not found then raise exception 'That code does not exist.'; end if;
  if inv.revoked_at is not null then raise exception 'That invite was revoked.'; end if;
  if inv.expires_at is not null and inv.expires_at < now() then
    raise exception 'That invite has expired.';
  end if;
  if inv.used_count >= inv.max_uses then
    raise exception 'That invite has already been used.';
  end if;
  if inv.email is not null and lower(inv.email) is distinct from lower(coalesce(my_email, '')) then
    raise exception 'That invite was issued to a different email address.';
  end if;

  resolved_name := coalesce(
    nullif(trim(coalesce(p_full_name, '')), ''),
    inv.full_name,
    (select full_name from profiles where id = me)
  );

  update profiles
     set household_id = inv.household_id,
         full_name    = resolved_name,
         initials     = coalesce(
                          nullif(upper(trim(coalesce(p_initials, ''))), ''),
                          inv.initials,
                          upper(left(resolved_name, 2))
                        ),
         color        = coalesce(inv.color, color),
         is_admin     = coalesce(inv.is_admin, false)
   where id = me;

  update household_invites set used_count = used_count + 1 where id = inv.id;

  perform add_to_rotations(me, inv.household_id);

  insert into activity_log (household_id, actor_id, verb, summary)
  values (inv.household_id, me, 'joined_household', resolved_name || ' joined the house');

  return inv.household_id;
end;
$$;

-- Admins can remove someone; the rotation closes up behind them.
create or replace function remove_member(p_profile uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  if not is_household_admin() then raise exception 'only an admin can remove someone'; end if;
  if p_profile = auth.uid() then raise exception 'you cannot remove yourself'; end if;

  select household_id into hh from profiles where id = auth.uid();
  if not exists (select 1 from profiles where id = p_profile and household_id = hh) then
    raise exception 'that person is not in your household';
  end if;

  perform remove_from_rotations(p_profile, hh);
  update profiles set household_id = null, is_admin = false where id = p_profile;
end;
$$;

create or replace function set_member_admin(p_profile uuid, p_is_admin boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  if not is_household_admin() then raise exception 'only an admin can change roles'; end if;
  select household_id into hh from profiles where id = auth.uid();

  update profiles set is_admin = p_is_admin
   where id = p_profile and household_id = hh;

  if not exists (select 1 from profiles where household_id = hh and is_admin) then
    raise exception 'a household needs at least one admin';
  end if;
end;
$$;

/* ------------------------------------------------------------ kiosk devices */

alter table kiosk_devices
  add column if not exists created_by uuid references profiles(id) on delete set null;

-- Pairing code is shown once at creation; only its hash is stored.
create or replace function create_kiosk_device(p_name text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  hh   uuid;
  code text;
begin
  if not is_household_admin() then raise exception 'only an admin can pair a kiosk'; end if;
  select household_id into hh from profiles where id = auth.uid();
  if hh is null then raise exception 'you are not in a household'; end if;

  code := encode(gen_random_bytes(24), 'base64');
  code := replace(replace(replace(code, '+', '-'), '/', '_'), '=', '');

  insert into kiosk_devices (household_id, name, token_hash, created_by)
  values (hh, coalesce(nullif(trim(p_name), ''), 'Kiosk'),
          encode(digest(code, 'sha256'), 'hex'), auth.uid());

  return code;
end;
$$;

-- Called by the pairing route with the service role; resolves a raw token to
-- the household it belongs to. Constant-time-ish: we look up by hash, never
-- compare secrets in application code.
create or replace function resolve_kiosk_token(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  update kiosk_devices
     set last_seen_at = now()
   where token_hash = encode(digest(p_token, 'sha256'), 'hex')
  returning household_id into hh;

  return hh;
end;
$$;

/* --------------------------------------------------------------------- RLS */

drop policy if exists inv_read on household_invites;
create policy inv_read on household_invites for select
  using (is_household_member(household_id));

drop policy if exists kiosk_read on kiosk_devices;
create policy kiosk_read on kiosk_devices for select
  using (is_household_member(household_id));

-- Membership and role changes go through the SECURITY DEFINER functions above.
-- Without this, `pr_write` lets anyone set their own household_id to another
-- household's uuid and read that entire house — harmless with one household,
-- a full data breach with two.
do $$
declare r text;
begin
  foreach r in array array['authenticated', 'domestic_app'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('revoke update on profiles from %I', r);
      execute format(
        'grant update (full_name, initials, color, avatar_url, notify_push,
                       notify_email, quiet_from, quiet_to) on profiles to %I', r);
      execute format('grant execute on all functions in schema public to %I', r);
    end if;
  end loop;
end $$;


/**************************************************************************
 * 0005_modules.sql
 *************************************************************************/

-- Every house runs differently. A household turns components on and off
-- instead of inheriting whatever 526 Detroit St. happens to do.
--
-- The registry itself lives in TypeScript (src/lib/modules.ts) — this table
-- only records which keys a household has enabled and any per-module settings,
-- so adding a module is a code change, not a migration.

create table if not exists household_modules (
  household_id uuid    not null references households(id) on delete cascade,
  module       text    not null,
  enabled      boolean not null default true,
  settings     jsonb   not null default '{}',
  updated_at   timestamptz not null default now(),
  updated_by   uuid references profiles(id) on delete set null,
  primary key (household_id, module)
);

alter table household_modules enable row level security;

drop policy if exists mod_read on household_modules;
create policy mod_read on household_modules for select
  using (is_household_member(household_id));

-- Writes go through set_module() so the admin check lives in one place.
create or replace function set_module(
  p_module   text,
  p_enabled  boolean,
  p_settings jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  if not is_household_admin() then
    raise exception 'only an admin can change what this household uses';
  end if;

  select household_id into hh from profiles where id = auth.uid();
  if hh is null then raise exception 'you are not in a household'; end if;

  insert into household_modules (household_id, module, enabled, settings, updated_by)
  values (hh, p_module, p_enabled, coalesce(p_settings, '{}'::jsonb), auth.uid())
  on conflict (household_id, module) do update
    set enabled    = excluded.enabled,
        settings   = coalesce(p_settings, household_modules.settings),
        updated_at = now(),
        updated_by = auth.uid();
end;
$$;

-- A household with no row for a module falls back to this. Keeping the default
-- in one function means an existing household picks up a newly shipped module
-- without a backfill.
create or replace function default_modules()
returns text[]
language sql
immutable
as $$
  select array['chores', 'expenses', 'kiosk'];
$$;

create or replace function enabled_modules(p_household uuid)
returns text[]
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    array_agg(m.module order by m.module) filter (where m.enabled),
    '{}'::text[]
  ) || (
    -- defaults that have never been explicitly toggled
    select coalesce(array_agg(d order by d), '{}'::text[])
    from unnest(default_modules()) d
    where not exists (
      select 1 from household_modules x
      where x.household_id = p_household and x.module = d
    )
  )
  from household_modules m
  where m.household_id = p_household;
$$;

-- New households start with the defaults written explicitly, so the admin
-- screen shows real toggles rather than implied state.
--
-- `create or replace` cannot add a parameter, even a defaulted one — it creates
-- an overload, and every existing 5-argument call then fails as ambiguous. Drop
-- the 0004 signature first.
drop function if exists create_household(text, text, text, text, text);

-- `or replace` so this file can be applied twice without erroring; the drop
-- above removes the 0004 five-argument signature, not this one.
create or replace function create_household(
  p_name      text,
  p_address   text default null,
  p_timezone  text default 'America/Detroit',
  p_full_name text default null,
  p_initials  text default null,
  p_modules   text[] default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  me       uuid := auth.uid();
  new_id   uuid;
  chore_id uuid;
  existing uuid;
  wanted   text[] := coalesce(p_modules, default_modules());
begin
  if me is null then
    raise exception 'not signed in';
  end if;

  select household_id into existing from profiles where id = me;
  if existing is not null then
    raise exception 'you are already in a household';
  end if;

  insert into households (name, address, timezone)
  values (trim(p_name), nullif(trim(coalesce(p_address, '')), ''), p_timezone)
  returning id into new_id;

  update profiles
     set household_id = new_id,
         is_admin     = true,
         full_name    = coalesce(nullif(trim(coalesce(p_full_name, '')), ''), full_name),
         initials     = coalesce(nullif(upper(trim(coalesce(p_initials, ''))), ''), initials)
   where id = me;

  insert into household_modules (household_id, module, enabled, updated_by)
  select new_id, d, d = any (wanted), me
  from unnest(default_modules()) d;

  -- Anything asked for that is not a default (a module shipped later) still
  -- gets recorded.
  insert into household_modules (household_id, module, enabled, updated_by)
  select new_id, w, true, me
  from unnest(wanted) w
  where not (w = any (default_modules()))
  on conflict do nothing;

  -- Starter chores only if this house actually does chores here.
  if 'chores' = any (wanted) then
    for chore_id in
      insert into chores (household_id, name, emoji, description, cadence,
                          days_of_week, interval_weeks, due_hour, queue_depth, sort_order)
      values
        (new_id, 'Floors', '🧹', 'Sweep and mop the common areas', 'scheduled', '{0,5}', 1, 20, 4, 1),
        (new_id, 'Microwave', '🍲', 'Wipe out the microwave', 'scheduled', '{6}', 2, 20, 4, 2),
        (new_id, 'Trash to curb', '🗑️', 'Bins out the night before pickup', 'scheduled', '{0}', 1, 19, 4, 3),
        (new_id, 'Dishes', '🍽️', 'Run and unload a load', 'on_demand', '{}', 1, 20, 4, 4),
        (new_id, 'Trash when full', '🚮', 'Swap the kitchen bag', 'on_demand', '{}', 1, 20, 4, 5)
      returning id
    loop
      insert into chore_rotation (chore_id, profile_id, position) values (chore_id, me, 0);
    end loop;

    for chore_id in select id from chores where household_id = new_id loop
      if (select cadence from chores where id = chore_id) = 'scheduled' then
        perform materialize_schedule(chore_id);
      else
        perform top_up_queue(chore_id);
      end if;
    end loop;
  end if;

  insert into activity_log (household_id, actor_id, verb, summary)
  values (new_id, me, 'created_household',
          (select full_name from profiles where id = me) || ' started the house');

  return new_id;
end;
$$;

-- Backfill: households that predate this table keep everything they had.
insert into household_modules (household_id, module, enabled)
select h.id, d, true
from households h, unnest(default_modules()) d
on conflict do nothing;


/**************************************************************************
 * 0006_devices.sql
 *************************************************************************/

-- The Home Assistant bridge had the same single-household assumption the kiosk
-- did: one shared token in an env var, resolved against "whichever household
-- exists". Both are really the same thing — a non-human device bound to one
-- house — so they share one registry and one token mechanism.

alter table kiosk_devices
  add column if not exists kind text not null default 'kiosk';

do $$
begin
  alter table kiosk_devices
    add constraint kiosk_devices_kind_check
    check (kind in ('kiosk', 'home_assistant'));
exception when duplicate_object then null;
end $$;

create or replace function create_device(p_name text, p_kind text default 'kiosk')
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  hh   uuid;
  code text;
begin
  if not is_household_admin() then raise exception 'only an admin can add a device'; end if;
  if p_kind not in ('kiosk', 'home_assistant') then
    raise exception 'unknown device kind %', p_kind;
  end if;

  select household_id into hh from profiles where id = auth.uid();
  if hh is null then raise exception 'you are not in a household'; end if;

  -- 24 bytes of CSPRNG, url-safe. Returned once; only the hash is kept.
  code := replace(replace(replace(encode(gen_random_bytes(24), 'base64'), '+', '-'), '/', '_'), '=', '');

  insert into kiosk_devices (household_id, name, kind, token_hash, created_by)
  values (hh, coalesce(nullif(trim(p_name), ''), 'Device'), p_kind,
          encode(digest(code, 'sha256'), 'hex'), auth.uid());

  return code;
end;
$$;

create or replace function resolve_device_token(p_token text, p_kind text default null)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  update kiosk_devices
     set last_seen_at = now()
   where token_hash = encode(digest(p_token, 'sha256'), 'hex')
     and (p_kind is null or kind = p_kind)
  returning household_id into hh;

  return hh;
end;
$$;

-- Kept as thin wrappers so existing callers keep working.
create or replace function create_kiosk_device(p_name text)
returns text
language sql
security definer
set search_path = public
as $$ select create_device(p_name, 'kiosk'); $$;

create or replace function resolve_kiosk_token(p_token text)
returns uuid
language sql
security definer
set search_path = public
as $$ select resolve_device_token(p_token, 'kiosk'); $$;


/**************************************************************************
 * 0007_intro.sql
 *************************************************************************/

-- Tracks whether someone has seen the "how this works" walkthrough. On the
-- profile rather than localStorage so it follows them across devices — you
-- should not get the tour again just because you opened it on the iPad.

alter table profiles
  add column if not exists intro_seen_at timestamptz;

-- 0004 revoked blanket UPDATE on profiles and re-granted it column by column,
-- so a new user-writable column has to be added to that grant explicitly.
do $$
declare r text;
begin
  foreach r in array array['authenticated', 'domestic_app'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('grant update (intro_seen_at) on profiles to %I', r);
    end if;
  end loop;
end $$;


/**************************************************************************
 * 0008_pgcrypto_schema.sql
 *************************************************************************/

-- pgcrypto does not live in `public` on Supabase.
--
-- Supabase pre-installs pgcrypto into the `extensions` schema, so 0001's
-- `create extension if not exists "pgcrypto"` is a no-op there and never moves
-- it into `public`. Stock Postgres has no such schema, so the same statement
-- installs it into `public` — which is why the device functions worked in the
-- test container and in local dev, and failed in production with
-- `function gen_random_bytes(integer) does not exist`.
--
-- Both device functions are `security definer` with `set search_path = public`,
-- which is what pins them to a schema that may not hold pgcrypto. Adding
-- `extensions` covers both layouts: Postgres silently ignores a schema in
-- search_path that does not exist, so this stays correct on stock Postgres.
--
-- Keep `extensions` on the search_path of any future security-definer function
-- that calls digest(), gen_random_bytes(), crypt(), or hmac().

-- Guarantee pgcrypto exists somewhere first. If it is already installed this
-- leaves it exactly where it is (in `public` on stock Postgres, `extensions` on
-- Supabase); if it is not installed at all, put it in `extensions`. Together
-- with the search_path below, all three layouts resolve.
do $$
begin
  if not exists (select 1 from pg_extension where extname = 'pgcrypto') then
    create schema if not exists extensions;
    create extension pgcrypto with schema extensions;
  end if;
end $$;

create or replace function create_device(p_name text, p_kind text default 'kiosk')
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  hh   uuid;
  code text;
begin
  if not is_household_admin() then raise exception 'only an admin can add a device'; end if;
  if p_kind not in ('kiosk', 'home_assistant') then
    raise exception 'unknown device kind %', p_kind;
  end if;

  select household_id into hh from profiles where id = auth.uid();
  if hh is null then raise exception 'you are not in a household'; end if;

  -- 24 bytes of CSPRNG, url-safe. Returned once; only the hash is kept.
  code := replace(replace(replace(encode(gen_random_bytes(24), 'base64'), '+', '-'), '/', '_'), '=', '');

  insert into kiosk_devices (household_id, name, kind, token_hash, created_by)
  values (hh, coalesce(nullif(trim(p_name), ''), 'Device'), p_kind,
          encode(digest(code, 'sha256'), 'hex'), auth.uid());

  return code;
end;
$$;

create or replace function resolve_device_token(p_token text, p_kind text default null)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare hh uuid;
begin
  update kiosk_devices
     set last_seen_at = now()
   where token_hash = encode(digest(p_token, 'sha256'), 'hex')
     and (p_kind is null or kind = p_kind)
  returning household_id into hh;

  return hh;
end;
$$;


/**************************************************************************
 * 0009_chore_admin.sql
 *************************************************************************/

-- Chores were seed-only: create_household() inserts a starter set and nothing
-- since then has let an admin add, edit, or retire one. This gives admins the
-- same "add/remove" power over chores that already exists for people
-- (household_invites, remove_member) and devices (kiosk_devices).
--
-- Precedent: household_invites and kiosk_devices carry only a SELECT policy —
-- writes are impossible except through a SECURITY DEFINER function that checks
-- is_household_admin() internally. `chores`/`chore_rotation` currently allow
-- any member to write directly (`ch_all`/`rot_all`), but nothing in the app
-- ever does — every client reference is a `.select(...)`. Tightening both
-- tables to the same read-only-plus-RPC shape closes that gap and gives chore
-- management the same admin boundary as everything else in this tier.

/* ------------------------------------------------------------------ create */

create or replace function create_chore(
  p_name           text,
  p_cadence        chore_cadence,
  p_emoji          text default '🧹',
  p_description    text default null,
  p_days_of_week   smallint[] default '{}',
  p_interval_weeks smallint default 1,
  p_due_hour       smallint default 20,
  p_queue_depth    smallint default 4,
  p_lookahead_days smallint default 21,
  p_profile_ids    uuid[] default '{}'
)
returns chores
language plpgsql
security definer
set search_path = public
as $$
declare
  hh        uuid;
  next_sort smallint;
  new_chore chores%rowtype;
begin
  if not is_household_admin() then raise exception 'only an admin can add a chore'; end if;
  select household_id into hh from profiles where id = auth.uid();
  if hh is null then raise exception 'you are not in a household'; end if;
  if coalesce(trim(p_name), '') = '' then raise exception 'give it a name'; end if;

  select coalesce(max(sort_order), 0) + 1 into next_sort from chores where household_id = hh;

  insert into chores (
    household_id, name, emoji, description, cadence,
    days_of_week, interval_weeks, due_hour, queue_depth, lookahead_days, sort_order
  )
  values (
    hh, trim(p_name), coalesce(nullif(trim(p_emoji), ''), '🧹'),
    nullif(trim(coalesce(p_description, '')), ''), p_cadence,
    coalesce(p_days_of_week, '{}'), greatest(coalesce(p_interval_weeks, 1), 1),
    coalesce(p_due_hour, 20), greatest(coalesce(p_queue_depth, 4), 1),
    greatest(coalesce(p_lookahead_days, 21), 1), next_sort
  )
  returning * into new_chore;

  if p_profile_ids is not null and array_length(p_profile_ids, 1) is not null then
    insert into chore_rotation (chore_id, profile_id, position)
    select new_chore.id, t.pid, t.ord - 1
    from unnest(p_profile_ids) with ordinality as t(pid, ord)
    where exists (select 1 from profiles where id = t.pid and household_id = hh);
  end if;

  if new_chore.cadence = 'scheduled' then
    perform materialize_schedule(new_chore.id);
  else
    perform top_up_queue(new_chore.id);
  end if;

  insert into activity_log (household_id, actor_id, verb, summary, metadata)
  values (hh, auth.uid(), 'created_chore', new_chore.name || ' was added to the board',
          jsonb_build_object('chore_id', new_chore.id, 'emoji', new_chore.emoji));

  return new_chore;
end;
$$;

/* -------------------------------------------------------------------- edit */

-- Cadence-affecting fields only touch `pending` turns — done/skipped/missed
-- rows are history and are never rewritten, same rule as resync_pending_turns.
create or replace function update_chore(
  p_chore          uuid,
  p_name           text default null,
  p_emoji          text default null,
  p_description    text default null,
  p_cadence        chore_cadence default null,
  p_days_of_week   smallint[] default null,
  p_interval_weeks smallint default null,
  p_due_hour       smallint default null,
  p_queue_depth    smallint default null,
  p_lookahead_days smallint default null,
  p_sort_order     smallint default null
)
returns chores
language plpgsql
security definer
set search_path = public
as $$
declare
  hh              uuid;
  before          chores%rowtype;
  after           chores%rowtype;
  cadence_changed boolean;
begin
  if not is_household_admin() then raise exception 'only an admin can edit a chore'; end if;
  select household_id into hh from profiles where id = auth.uid();

  select * into before from chores where id = p_chore and household_id = hh;
  if not found then raise exception 'that chore is not in your household'; end if;

  update chores set
    name           = coalesce(nullif(trim(p_name), ''), name),
    emoji          = coalesce(nullif(trim(p_emoji), ''), emoji),
    description    = case when p_description is not null
                          then nullif(trim(p_description), '') else description end,
    cadence        = coalesce(p_cadence, cadence),
    days_of_week   = coalesce(p_days_of_week, days_of_week),
    interval_weeks = coalesce(p_interval_weeks, interval_weeks),
    due_hour       = coalesce(p_due_hour, due_hour),
    queue_depth    = coalesce(p_queue_depth, queue_depth),
    lookahead_days = coalesce(p_lookahead_days, lookahead_days),
    sort_order     = coalesce(p_sort_order, sort_order)
  where id = p_chore
  returning * into after;

  cadence_changed :=
    after.cadence        is distinct from before.cadence or
    after.days_of_week   is distinct from before.days_of_week or
    after.interval_weeks is distinct from before.interval_weeks or
    after.due_hour       is distinct from before.due_hour or
    after.queue_depth    is distinct from before.queue_depth;

  if cadence_changed then
    delete from chore_turns where chore_id = p_chore and status = 'pending';
    if after.cadence = 'scheduled' then
      perform materialize_schedule(p_chore);
    else
      perform top_up_queue(p_chore);
    end if;
  end if;

  return after;
end;
$$;

/* ------------------------------------------------------------ active state */

-- One toggle covers both directions: deactivating hides a chore from the
-- board without touching its history (chore_turns still references it);
-- reactivating just needs the queue/schedule filled back in.
create or replace function set_chore_active(p_chore uuid, p_active boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  hh     uuid;
  chore  chores%rowtype;
begin
  if not is_household_admin() then raise exception 'only an admin can do that'; end if;
  select household_id into hh from profiles where id = auth.uid();

  update chores set is_active = p_active
   where id = p_chore and household_id = hh
  returning * into chore;
  if not found then raise exception 'that chore is not in your household'; end if;

  if p_active then
    if chore.cadence = 'scheduled' then
      perform materialize_schedule(p_chore);
    else
      perform top_up_queue(p_chore);
    end if;
  end if;
end;
$$;

/* --------------------------------------------------------------- rotation */

-- Replaces a chore's entire roster in one call — add, remove, and reorder are
-- all just "submit the new ordered list", so the UI needs one primitive
-- instead of three. Positions come straight from the submitted array's order
-- (via `with ordinality`), which is simpler than deriving them from existing
-- row order the way remove_from_rotations does for a single deletion.
create or replace function set_chore_rotation(p_chore uuid, p_profile_ids uuid[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  if not is_household_admin() then raise exception 'only an admin can edit a chore roster'; end if;
  select household_id into hh from profiles where id = auth.uid();
  if not exists (select 1 from chores where id = p_chore and household_id = hh) then
    raise exception 'that chore is not in your household';
  end if;
  if exists (
    select 1 from unnest(coalesce(p_profile_ids, '{}')) pid
    where not exists (select 1 from profiles where id = pid and household_id = hh)
  ) then
    raise exception 'everyone on the rotation must be in your household';
  end if;

  delete from chore_rotation where chore_id = p_chore;

  insert into chore_rotation (chore_id, profile_id, position)
  select p_chore, t.pid, t.ord - 1
  from unnest(coalesce(p_profile_ids, '{}')) with ordinality as t(pid, ord);

  perform resync_pending_turns(p_chore);
end;
$$;

/* --------------------------------------------------------------------- RLS */

drop policy if exists ch_all on chores;
drop policy if exists ch_read on chores;
create policy ch_read on chores for select
  using (is_household_member(household_id));

drop policy if exists rot_all on chore_rotation;
drop policy if exists rot_read on chore_rotation;
create policy rot_read on chore_rotation for select
  using (exists (select 1 from chores c where c.id = chore_id and is_household_member(c.household_id)));


/**************************************************************************
 * 0010_recurring_expenses.sql
 *************************************************************************/

-- Rent, subscriptions, and other bills that repeat on a schedule and should
-- just show up in the ledger without anyone remembering to add them.
--
-- Splits are computed once, in TypeScript, using the same splitEqual /
-- splitByWeight helpers addExpense already uses for one-off expenses — the
-- resulting owed_cents (and weight, kept for re-editing exactly like
-- expense_splits.weight) are stored per participant. Posting a due occurrence
-- is then a pure copy, not a re-derivation, so there is no separate plpgsql
-- port of the splitting math to keep in sync with money.ts.
--
-- Management (create/edit/pause) follows the household_invites /
-- kiosk_devices / chores shape: the tables carry only a SELECT policy, and
-- every write goes through a SECURITY DEFINER function that checks
-- is_household_admin(). A recurring expense is standing configuration that
-- re-fires forever with no per-occurrence confirmation, unlike a one-off
-- expense that is reviewed once at creation — that risk profile matches the
-- admin-gated tier, not the member-writable tier expenses/settlements sit in.
--
-- Posting itself (post_due_recurring_expenses) is different in kind: it runs
-- with no user session, invoked by cron via the admin client exactly like
-- materialize_schedule/top_up_queue, must be all-or-nothing per occurrence,
-- and must be safe to call twice a day — the "atomic, cron-invoked" category
-- CLAUDE.md calls out for plpgsql, same as its chores counterparts.

create table if not exists recurring_expenses (
  id               uuid primary key default gen_random_uuid(),
  household_id     uuid not null references households(id) on delete cascade,
  description      text not null,
  amount_cents     bigint not null check (amount_cents > 0),
  currency         char(3) not null default 'USD',
  category         text not null default 'general',
  paid_by          uuid not null references profiles(id) on delete restrict,
  split_kind       split_kind not null default 'equal',

  -- Two cadence families, each with a multiplier: weekly x1 = weekly, x2 =
  -- biweekly; monthly x1 = monthly, x3 = quarterly. day_of_month is clamped to
  -- the last day of short months when posting.
  cadence          text not null check (cadence in ('weekly', 'monthly')),
  interval_weeks   smallint not null default 1 check (interval_weeks > 0),
  interval_months  smallint not null default 1 check (interval_months > 0),
  day_of_month     smallint check (day_of_month between 1 and 31),
  check (cadence = 'weekly' or day_of_month is not null),

  next_run_on      date not null default current_date,
  is_active        boolean not null default true,
  created_by       uuid references profiles(id) on delete set null,
  created_at       timestamptz not null default now()
);

create index if not exists recurring_expenses_household_id_is_active_idx
  on recurring_expenses (household_id, is_active);

create table if not exists recurring_expense_participants (
  recurring_expense_id uuid   not null references recurring_expenses(id) on delete cascade,
  profile_id            uuid   not null references profiles(id) on delete cascade,
  owed_cents            bigint not null check (owed_cents >= 0),
  weight                numeric(10,4),
  primary key (recurring_expense_id, profile_id)
);

/* --------------------------------------------------------------- management */

create or replace function create_recurring_expense(
  p_description     text,
  p_amount_cents    bigint,
  p_paid_by         uuid,
  p_split_kind      split_kind,
  p_cadence         text,
  p_participants    jsonb,  -- [{"profile_id": uuid, "owed_cents": int, "weight": numeric|null}, ...]
  p_category        text default 'general',
  p_interval_weeks  smallint default 1,
  p_interval_months smallint default 1,
  p_day_of_month    smallint default null,
  p_start_on        date default current_date
)
returns recurring_expenses
language plpgsql
security definer
set search_path = public
as $$
declare
  hh      uuid;
  total   bigint;
  row_out recurring_expenses%rowtype;
begin
  if not is_household_admin() then raise exception 'only an admin can add a recurring expense'; end if;
  select household_id into hh from profiles where id = auth.uid();
  if hh is null then raise exception 'you are not in a household'; end if;

  if p_cadence not in ('weekly', 'monthly') then raise exception 'unknown cadence %', p_cadence; end if;
  if p_cadence = 'monthly' and p_day_of_month is null then
    raise exception 'a monthly recurring expense needs a day of the month';
  end if;
  if not exists (select 1 from profiles where id = p_paid_by and household_id = hh) then
    raise exception 'the payer must be in your household';
  end if;
  if jsonb_array_length(coalesce(p_participants, '[]'::jsonb)) = 0 then
    raise exception 'split it with someone';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(p_participants) as x(profile_id uuid, owed_cents bigint, weight numeric)
    where not exists (select 1 from profiles where id = x.profile_id and household_id = hh)
  ) then
    raise exception 'everyone in the split must be in your household';
  end if;

  select sum(x.owed_cents) into total
  from jsonb_to_recordset(p_participants) as x(profile_id uuid, owed_cents bigint, weight numeric);
  if total is distinct from p_amount_cents then
    raise exception 'splits must add up to the total';
  end if;

  insert into recurring_expenses (
    household_id, description, amount_cents, category, paid_by, split_kind,
    cadence, interval_weeks, interval_months, day_of_month, next_run_on, created_by
  )
  values (
    hh, trim(p_description), p_amount_cents, coalesce(p_category, 'general'), p_paid_by, p_split_kind,
    p_cadence, greatest(coalesce(p_interval_weeks, 1), 1), greatest(coalesce(p_interval_months, 1), 1),
    p_day_of_month, coalesce(p_start_on, current_date), auth.uid()
  )
  returning * into row_out;

  insert into recurring_expense_participants (recurring_expense_id, profile_id, owed_cents, weight)
  select row_out.id, x.profile_id, x.owed_cents, x.weight
  from jsonb_to_recordset(p_participants) as x(profile_id uuid, owed_cents bigint, weight numeric);

  insert into activity_log (household_id, actor_id, verb, summary, metadata)
  values (hh, auth.uid(), 'created_recurring_expense',
          row_out.description || ' will repeat ' || row_out.cadence,
          jsonb_build_object('recurring_expense_id', row_out.id));

  return row_out;
end;
$$;

create or replace function update_recurring_expense(
  p_id              uuid,
  p_description     text default null,
  p_amount_cents    bigint default null,
  p_paid_by         uuid default null,
  p_split_kind      split_kind default null,
  p_category        text default null,
  p_cadence         text default null,
  p_interval_weeks  smallint default null,
  p_interval_months smallint default null,
  p_day_of_month    smallint default null,
  p_participants    jsonb default null
)
returns recurring_expenses
language plpgsql
security definer
set search_path = public
as $$
declare
  hh         uuid;
  before     recurring_expenses%rowtype;
  row_out    recurring_expenses%rowtype;
  total      bigint;
  new_amount bigint;
begin
  if not is_household_admin() then raise exception 'only an admin can edit a recurring expense'; end if;
  select household_id into hh from profiles where id = auth.uid();

  select * into before from recurring_expenses where id = p_id and household_id = hh;
  if not found then raise exception 'that recurring expense is not in your household'; end if;

  if p_cadence is not null and p_cadence not in ('weekly', 'monthly') then
    raise exception 'unknown cadence %', p_cadence;
  end if;
  if coalesce(p_cadence, before.cadence) = 'monthly'
     and coalesce(p_day_of_month, before.day_of_month) is null then
    raise exception 'a monthly recurring expense needs a day of the month';
  end if;
  if p_paid_by is not null and not exists (select 1 from profiles where id = p_paid_by and household_id = hh) then
    raise exception 'the payer must be in your household';
  end if;

  new_amount := coalesce(p_amount_cents, before.amount_cents);

  if p_participants is not null then
    if exists (
      select 1 from jsonb_to_recordset(p_participants) as x(profile_id uuid, owed_cents bigint, weight numeric)
      where not exists (select 1 from profiles where id = x.profile_id and household_id = hh)
    ) then
      raise exception 'everyone in the split must be in your household';
    end if;
    select sum(x.owed_cents) into total
    from jsonb_to_recordset(p_participants) as x(profile_id uuid, owed_cents bigint, weight numeric);
    if total is distinct from new_amount then
      raise exception 'splits must add up to the total';
    end if;
  end if;

  update recurring_expenses set
    description     = coalesce(nullif(trim(p_description), ''), description),
    amount_cents    = new_amount,
    paid_by         = coalesce(p_paid_by, paid_by),
    split_kind      = coalesce(p_split_kind, split_kind),
    category        = coalesce(p_category, category),
    cadence         = coalesce(p_cadence, cadence),
    interval_weeks  = coalesce(p_interval_weeks, interval_weeks),
    interval_months = coalesce(p_interval_months, interval_months),
    day_of_month    = coalesce(p_day_of_month, day_of_month)
  where id = p_id
  returning * into row_out;

  if p_participants is not null then
    delete from recurring_expense_participants where recurring_expense_id = p_id;
    insert into recurring_expense_participants (recurring_expense_id, profile_id, owed_cents, weight)
    select p_id, x.profile_id, x.owed_cents, x.weight
    from jsonb_to_recordset(p_participants) as x(profile_id uuid, owed_cents bigint, weight numeric);
  end if;

  return row_out;
end;
$$;

create or replace function set_recurring_expense_active(p_id uuid, p_active boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  if not is_household_admin() then raise exception 'only an admin can do that'; end if;
  select household_id into hh from profiles where id = auth.uid();
  update recurring_expenses set is_active = p_active where id = p_id and household_id = hh;
  if not found then raise exception 'that recurring expense is not in your household'; end if;
end;
$$;

/* ------------------------------------------------------------------ posting */

-- Catches up on any missed cycles (server downtime, a skipped cron run) one
-- occurrence at a time, capped so a bug can never spin this into a runaway
-- loop. Idempotent across the twice-daily cron: next_run_on is advanced past
-- `today` inside the same statement that inserts the expense, so a second run
-- later that day sees next_run_on > today and does nothing for that row.
create or replace function post_due_recurring_expenses()
returns setof expenses
language plpgsql
security definer
set search_path = public
as $$
declare
  r           recurring_expenses%rowtype;
  tz          text;
  today       date;
  new_expense expenses%rowtype;
  next_date   date;
  guard       int;
begin
  for r in select * from recurring_expenses where is_active for update loop
    select timezone into tz from households where id = r.household_id;
    today := (now() at time zone coalesce(tz, 'America/Detroit'))::date;
    guard := 0;

    while r.next_run_on <= today and guard < 24 loop
      insert into expenses (
        household_id, description, amount_cents, currency, category,
        paid_by, spent_on, split_kind, created_by, note
      )
      values (
        r.household_id, r.description, r.amount_cents, r.currency, r.category,
        r.paid_by, r.next_run_on, r.split_kind, r.created_by, 'Recurring'
      )
      returning * into new_expense;

      insert into expense_splits (expense_id, profile_id, owed_cents, weight)
      select new_expense.id, p.profile_id, p.owed_cents, p.weight
      from recurring_expense_participants p
      where p.recurring_expense_id = r.id;

      insert into activity_log (household_id, actor_id, verb, summary, metadata)
      values (r.household_id, r.created_by, 'added_expense',
              r.description || ' — ' || to_char(r.amount_cents / 100.0, 'FM$999999990.00') || ' (recurring)',
              jsonb_build_object('expense_id', new_expense.id, 'recurring_expense_id', r.id));

      if r.cadence = 'weekly' then
        next_date := r.next_run_on + (r.interval_weeks * 7);
      else
        next_date := (date_trunc('month', r.next_run_on) + (r.interval_months || ' months')::interval)::date;
        next_date := next_date + (
          least(r.day_of_month, extract(day from (next_date + interval '1 month - 1 day'))::int) - 1
        );
      end if;
      r.next_run_on := next_date;
      update recurring_expenses set next_run_on = next_date where id = r.id;

      return next new_expense;
      guard := guard + 1;
    end loop;
  end loop;
  return;
end;
$$;

/* --------------------------------------------------------------------- RLS */

alter table recurring_expenses enable row level security;
alter table recurring_expense_participants enable row level security;

drop policy if exists rec_exp_read on recurring_expenses;
create policy rec_exp_read on recurring_expenses for select
  using (is_household_member(household_id));

drop policy if exists rec_part_read on recurring_expense_participants;
create policy rec_part_read on recurring_expense_participants for select
  using (exists (
    select 1 from recurring_expenses r
    where r.id = recurring_expense_id and is_household_member(r.household_id)
  ));


/**************************************************************************
 * 0011_ai_config.sql
 *************************************************************************/

-- Receipt scanning was wired to a single global ANTHROPIC_API_KEY env var,
-- picked up implicitly by `new Anthropic()`. That does not fit "any household
-- can deploy and run themselves" — each deployed house should be able to pick
-- its own provider (Anthropic or Gemini) and supply its own key.
--
-- An API key is a bearer credential, not a UI preference, so it does not live
-- in household_modules.settings — that column is readable by any member via
-- the existing mod_read policy. household_ai_config instead carries RLS with
-- *zero* policies: RLS enabled and no policy of any kind denies every row to
-- every client role, including this household's own admin browsing the app —
-- only a SECURITY DEFINER function (or the service role, which bypasses RLS
-- entirely) can read or write it. The key is additionally encrypted with
-- pgcrypto, already installed for this project (0008) — RLS stops the app's
-- normal query paths, encryption is the second layer that protects a Postgres
-- dump, backup, or read replica from leaking a raw vendor API key.
--
-- The encryption secret is passed as an argument on every call, not stored as
-- a Postgres GUC, so it stays inside this app's existing "secrets live in
-- .env" convention rather than adding a second secret-management surface.

create table if not exists household_ai_config (
  household_id  uuid primary key references households(id) on delete cascade,
  provider      text not null check (provider in ('anthropic', 'gemini')),
  api_key_enc   bytea not null,
  updated_at    timestamptz not null default now(),
  updated_by    uuid references profiles(id) on delete set null
);

alter table household_ai_config enable row level security;
-- Deliberately no policy at all — see comment above.

create or replace function set_ai_config(p_provider text, p_api_key text, p_secret text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare hh uuid;
begin
  if not is_household_admin() then raise exception 'only an admin can change this'; end if;
  if p_provider not in ('anthropic', 'gemini') then raise exception 'unknown provider %', p_provider; end if;
  if coalesce(trim(p_api_key), '') = '' then raise exception 'enter an API key'; end if;

  select household_id into hh from profiles where id = auth.uid();
  if hh is null then raise exception 'you are not in a household'; end if;

  insert into household_ai_config (household_id, provider, api_key_enc, updated_by)
  values (hh, p_provider, pgp_sym_encrypt(p_api_key, p_secret), auth.uid())
  on conflict (household_id) do update
    set provider    = excluded.provider,
        api_key_enc = excluded.api_key_enc,
        updated_at  = now(),
        updated_by  = auth.uid();
end;
$$;

create or replace function clear_ai_config()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare hh uuid;
begin
  if not is_household_admin() then raise exception 'only an admin can change this'; end if;
  select household_id into hh from profiles where id = auth.uid();
  delete from household_ai_config where household_id = hh;
end;
$$;

-- Enough for the admin settings screen to render "Anthropic — configured";
-- never returns the key, so this is safe to call from anywhere a signed-in
-- member can reach, not just admins.
create or replace function get_ai_config_summary()
returns table(provider text, updated_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select c.provider, c.updated_at
  from household_ai_config c
  join profiles p on p.household_id = c.household_id
  where p.id = auth.uid();
$$;

-- Used only from server-side code (the receipt route), never a client
-- component — the decrypted key must never appear in a response body.
create or replace function get_ai_credentials(p_secret text)
returns table(provider text, api_key text)
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare hh uuid;
begin
  select household_id into hh from profiles where id = auth.uid();
  if hh is null then return; end if;
  return query
    select c.provider, pgp_sym_decrypt(c.api_key_enc, p_secret)
    from household_ai_config c
    where c.household_id = hh;
end;
$$;
